### ISSUE TITLE
Linux: cannot initialize libvlc

### ISSUE THREAD

**Issue by djiamnot** [ue4plugins/VlcMedia#24] opened 2016-09-15 20:26 UTC
Hello,
Having a little trouble here. I'm getting the following error when loading the plugin:
```
[2016.09.15-19.07.54:603][  0]LogLinux:Warning: dlopen failed: <$HOME>/src/iesource/Plugins/VlcMedia/ThirdParty/vlc/Linux/x86_64-unknown-linux-gnu/libvlccore.so: file too short
[2016.09.15-19.07.54:603][  0]Warning: VlcMedia: Failed to load required library libvlccore.so. Plug-in will not be functional.
[2016.09.15-19.07.54:603][  0]LogVlcMedia:Error: Failed to initialize libvlc
```
The interesting part is that even when I hard-code the libvlc path to `/usr/lib` in VlcMediaBuild.cs, the plugin still seems to want the provided binaries. I seem to have the same vlc version installed on my system. I attach my modified version of [VlcMedia.Build.cs.txt](https://github.com/ue4plugins/VlcMedia/files/475520/VlcMedia.Build.cs.txt) with some logging added.

This is on Mint18, vlxMedia plugin tag 4.13.1, EU4 tag branch 4.13.

**Comment by gmpreussner** [comment] 2016-09-15 21:20
Yeah, it's loading the libraries in Vlc.cpp, Line 125, FVlc::Initialize(), so updating the Build.cs is not enough. We still need to figure out how to support Linux. The main decision to be made is which pre-compiled binaries we wish to include. It will probably be Ubuntu, but even there are different versions. And it is not clear how we better support other Linux distros. The initialization code will likely need some changes for that to work.

I'm going to close this out as a duplicate of https://github.com/ue4plugins/VlcMedia/issues/17

**Closed by gmpreussner** 2016-09-15 21:20 UTC
