### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by KhArtNJava** [ue4plugins/VlcMedia#2] opened 2015-06-26 12:49 UTC
Hello, Gerke Max Preussner.

I compiled UE source with your plugin. 

After that I disabled WMF plugin in my project settings: 

http://www.quirksmode.org/html5/videos/big_buck_bunny.mp4

![alt text][1]

and I keep enabled your VLC plugin:
![alt text][2]

After that I set up MediaPlayer:
![alt text][3]

After that when I press Play button - "Stopped" flashed and nothing happened.

It still not working? :)

  [1]: http://s6.postimg.org/pwzel39m9/screenshot_172.png
  [2]: http://s6.postimg.org/kmuftspdd/screenshot_173.png
  [3]: http://s6.postimg.org/y51c631ip/screenshot_174.png

**Comment by KhArtNJava** [comment] 2015-06-26 15:21
I found interesting things right now...
I've modified some files:
Vlc.cpp:
```
#define VLC_IMPORT(Name, Func) \
	Func = (FLibvlc##Func##Proc)FPlatformProcess::GetDllExport(LibHandle, TEXT(#Name)); \
	UE_LOG(LogVlcMedia, Warning, TEXT("VLC: LOADING VLC function %s"), TEXT(#Name)); \
	if (Func == nullptr) \
	{ \
		UE_LOG(LogVlcMedia, Warning, TEXT("Failed to import VLC function %s"), TEXT(#Name)); \
		Shutdown(); \
		return false; \
	}
```

It got to me text, that illustrated, that functions load was successful:
```
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_new
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_release
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_retain
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_errmsg
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_clearerr
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_event_attach
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_event_detach
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_event_type_name
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_event_manager
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_new_callbacks
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_new_location
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_new_path
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_parse_async
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_release
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_retain
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_tracks_get
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_tracks_release
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_event_manager
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_get_media
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_new
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_new_from_media
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_release
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_retain
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_set_media
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_get_fps
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_get_length
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_get_position
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_get_rate
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_get_state
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_get_time
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_is_seekable
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_set_position
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_set_rate
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_set_time
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_is_playing
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_pause
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_play
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_set_pause
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_stop
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_media_player_will_play
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_audio_get_track
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_audio_set_track
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_video_get_height
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_video_get_width
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_video_set_callbacks
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_video_set_format
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_video_get_spu
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_video_set_spu
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_video_get_track
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_video_set_track
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_audio_get_track_description
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_video_get_spu_description
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_video_get_track_description
LogVlcMedia:Warning: VLC: LOADING VLC function libvlc_track_description_release
```

After that, I modified file VlcMediaPlayer.cpp:
```
bool FVlcMediaPlayer::Open(const FString& Url)
{
	UE_LOG(LogVlcMedia, Warning, TEXT("VLC: FVlcMediaPlayer::Open %s"), *Url);

	if (Url.IsEmpty())
	{

		UE_LOG(LogVlcMedia, Warning, TEXT("VLC: FVlcMediaPlayer:: (Url.IsEmpty() "));
		return false;
	}

	Close();

	UE_LOG(LogVlcMedia, Warning, TEXT("VLC: FVlcMediaPlayer:: After Close(); "));


	FLibvlcMedia* NewMedia = nullptr;
		if (Url.Contains(TEXT("://"))) {
			UE_LOG(LogVlcMedia, Warning, TEXT("VLC: FVlcMediaPlayer:: NewMedia IS URL "));
			NewMedia = FVlc::MediaNewLocation(VlcInstance, TCHAR_TO_ANSI(*Url));
		}
		else {
			UE_LOG(LogVlcMedia, Warning, TEXT("VLC: FVlcMediaPlayer:: NewMedia IS FILE SYSTEM"));
			NewMedia = FVlc::MediaNewPath(VlcInstance, TCHAR_TO_ANSI(*Url));
		}

	if (NewMedia == nullptr)
	{

		UE_LOG(LogVlcMedia, Warning, TEXT("VLC: FVlcMediaPlayer:: NewMedia == nullptr "));
		return false;
	}

	MediaUrl = Url;

	return InitializeMediaPlayer(NewMedia);
}
```

and I found. that 
```
NewMedia = FVlc::MediaNewPath(VlcInstance, TCHAR_TO_ANSI(*Url));
```
always returns nullptr:
```
LogVlcMedia:Warning: VLC:  ___ M:/Downloads/Мультфильмы/Simpsons 03/03_01 - Stark Raving Dad.avi ____ 
LogVlcMedia:Warning: VLC: Extension - avi 
LogVlcMedia:Warning: VLC: FVlcMediaPlayer::Open M:/Downloads/Мультфильмы/Simpsons 03/03_01 - Stark Raving Dad.avi
LogVlcMedia:Warning: VLC: FVlcMediaPlayer:: After Close(); 
LogVlcMedia:Warning: VLC: FVlcMediaPlayer:: NewMedia IS FILE SYSTEM
LogVlcMedia:Warning: VLC: FVlcMediaPlayer:: NewMedia == nullptr 
```

```
LogVlcMedia:Warning: VLC:  ___ M:/Downloads/Мультфильмы/American.Dad.S01.HQ-DVDRip.x264.MIF/American.Dad.1x03.Stan.Knows.Best.DVDRip.x264.MIF.mkv ____ 
LogVlcMedia:Warning: VLC: Extension - mkv 
LogVlcMedia:Warning: VLC: FVlcMediaPlayer::Open M:/Downloads/Мультфильмы/American.Dad.S01.HQ-DVDRip.x264.MIF/American.Dad.1x03.Stan.Knows.Best.DVDRip.x264.MIF.mkv
LogVlcMedia:Warning: VLC: FVlcMediaPlayer:: After Close(); 
LogVlcMedia:Warning: VLC: FVlcMediaPlayer:: NewMedia IS FILE SYSTEM
LogVlcMedia:Warning: VLC: FVlcMediaPlayer:: NewMedia == nullptr 
```

How to fix it?

**Comment by gmpreussner** [comment] 2015-06-26 20:42
I can repro the problem. Something broke. I'm looking into it now.

**Comment by gmpreussner** [comment] 2015-06-26 22:35
So, the problem is our normalized file names. LibVLC will choke on a path with forward slashes if running on Windows. Something like the following almost works.

`
	FLibvlcMedia* NewMedia = (Url.Contains(TEXT("://")))
		? FVlc::MediaNewLocation(VlcInstance, TCHAR_TO_ANSI(*Url))
#if PLATFORM_WINDOWS
		: FVlc::MediaNewPath(VlcInstance, TCHAR_TO_ANSI(*Url.Replace(TEXT("/"), TEXT("\\"))));
#else
		: FVlc::MediaNewPath(VlcInstance, TCHAR_TO_ANSI(*Url));
#endif
`

However, there are other problems. I need to rethink how we handle media files in all of the plug-ins, because we cannot allow the third-party libraries to open files like we do right now. Media files may be deployed inside a .pak file where they are inaccessible to third-party libs. We have to pipe all file I/O through the platform file API in UE4 instead.

This will be part of a larger refactor. I'll try to look into it over the weekend.

**Comment by gmpreussner** [comment] 2015-06-27 01:49
I checked in some more changes to refactor the plug-ins handling of local media files. The files are loaded via UE4's platform file code and streamed into VLC via its media callback API. Unfortunately, this is not working as expected. I started a post on the VideoLAN forums: https://forum.videolan.org/viewtopic.php?f=32&t=126980

If you sync VlcMedia to head, make sure you also get https://github.com/EpicGames/UnrealEngine/commit/dbfec7de7564b20168eb8d106f2d0669a038df20 from UE4 Master as I changed the IMediaPlayer API.

**Comment by KhArtNJava** [comment] 2015-06-27 09:45
Wow! 
I have always had respect for the programmers so cool as you. Unfortunately, I still not so steep as you. )))
As I see, https://forum.videolan.org/viewtopic.php?f=32&t=126980 has answer from someone...

**Comment by gmpreussner** [comment] 2015-06-27 11:19
Ok, I found the problem. Working on a fix now!

**Comment by KhArtNJava** [comment] 2015-06-27 11:23
Hi... 
There are some problem in UE 4 master repo - https://github.com/EpicGames/UnrealEngine/commit/a8c29eb9f1ee02ac2610ce7e04dc94a02a8e3d77
@mkuhlens Added 
```
UMovieSceneTrack* ShotTrack = MovieScene->GetShotTrack();
``` 
I can't find MovieScene->GetShotTrack() anywhere...
Because of this I can't compile UE 4 from master...
Can you fix it?

**Comment by gmpreussner** [comment] 2015-06-27 12:50
Master should be fixed now.

**Comment by KhArtNJava** [comment] 2015-06-27 12:50
Yep, I see
https://github.com/EpicGames/UnrealEngine/commit/d5e0c3ab27ed06af830502368fd24a027f268325

**Closed** 2015-06-27 13:09 UTC

**Comment by gmpreussner** [comment] 2015-06-27 13:12
Alright, this should work better now. You will need to get another change from Master as well, which is not pushed to GitHub yet, but should be shortly.

**Comment by gmpreussner** [comment] 2015-06-27 13:13
https://github.com/EpicGames/UnrealEngine/commit/5e7a0d565aec65831ba54bbd9f0be669c543fef0

**Comment by KhArtNJava** [comment] 2015-06-27 13:21
Thank you...

Please advice, is it possible to compile UE for Windows on Linux?

My client machine is weak and all my servers on Linux...

**Comment by gmpreussner** [comment] 2015-06-27 13:24
Hmm.... good question, I don't know. It's possible to compile Linux from Windows, but I don't think we have a cross-compile tool chain the other way around. Might wanna check on AnswerHub for that.

**Comment by KhArtNJava** [comment] 2015-06-27 13:29
I asked it https://answers.unrealengine.com/questions/245490/is-it-possible-to-make-nightlybuilds-on-linux.html but still no answers... I knew about compiling for Linux on Windows... But I haven't servers on  Windows...

**Comment by gmpreussner** [comment] 2015-06-27 13:32
Ok, I will forward your question to our Linux guy.

**Comment by gmpreussner** [comment] 2015-06-27 13:35
And thanks for your help on this plug-in! If you find any more problems (I'm sure there are plenty), please open new issues.

One thing I noticed is that VLC seems to be automatically playing a video once after opening it. I will look into that next.

**Comment by KhArtNJava** [comment] 2015-06-27 13:39
I would be very grateful to your team if I compile on Linux as a UE, and my game. May be something like command line script, like Setup.sh with some option like "--compile-for-windows" and build tools for game packaging for Windows on Linux hosts...
It would be so cool to build nightly builds of games or UE editor on Linux servers to not waste client's machine's time and to not waste money for Windows licences...

**Comment by KhArtNJava** [comment] 2015-06-27 21:59
It's worked!
You are great!
But it crashed once. 
https://answers.unrealengine.com/storage/attachments/48162-logs.zip

**Comment by gmpreussner** [comment] 2015-06-28 01:54
Can you create a new issue and provide repro steps? If you could share the video file in question, that would be great, too. Looking at the log, it seems that VLC is throwing a bunch of errors, but without further instructions I can't do much right now. Thanks!
